base:
  数据存储位置:
    description: 数据存储位置
    config:
      数据存储位置: local

components:
  llm:
    description: 用于配置大模型相关信息
    config:
      api_key: 请输入api_key
      api_url: ""
      model: gpt-4-1106-preview
  
  browser: 
    description: 配置本电脑的浏览器信息，用于浏览器自动化
    config:
      浏览器类型: edge




