[tool.poetry]
name = "automate"
version = "0.1.0"
description = ""
authors = ["yuruotong"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "6.0.1"
requests = "2.31.0"
selenium = "4.16.0"
webdriver-manager = "4.0.1"
langchain = "0.1.7"
langchain-openai = "0.0.6"
pytest = "^8.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
