[tool.poetry]
name = "automate"
version = "0.1.0"
description = ""
authors = ["yuruotong"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
PyYAML = "6.0.1"
requests = "2.31.0"
selenium = "4.16.0"
webdriver-manager = "4.0.1"
langchain = "0.1.7"
langchain-openai = "0.0.6"
pytest = "^8.0.1"
pyqt6 = "^6.6.1"
leancloud = "^2.9.12"
pyautogui = "^0.9.54"
langchainhub = "^0.1.15"
pyinstaller = "^6.5.0"
pygments = "^2.17.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "default"
url = 'https://pypi.org/'
priority = "primary"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "supplemental"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
priority = "supplemental"